/*

 SKY_BKG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : G:\EclipseWorkSpaceforC++\Gameboy\Bakcground-Dayo.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/


#define sky_bkgWidth 40
#define sky_bkgHeight 18
#define sky_bkgBank 0

extern unsigned char sky_bkg[];

/* End of SKY_BKG.H */
